name: Deploy static content to Surge.sh

on:
  push:
    branches: ["main"]

concurrency:
  group: "surge"
  cancel-in-progress: true
  
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        id: pages
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          npm install -g surge
          surge --project ./dist --token ${{ secrets.SURGE_TOKEN }}

